// template_codegen renders source files from a spec with text/template and
// writes them into the interpreter's virtual filesystem, which the host then
// reads back. It is the practical counterpart to examples/templates: the same
// RenderString call, used as a code generator rather than a report renderer,
// and combined with the two capabilities that make that useful — a VFS the
// guest can write to, and a host that inspects the result afterwards.
//
// Nothing here touches the real disk. The guest writes to nanoGo's in-memory
// VFS, and the host reads the generated files out of that same VFS, so a
// generator can be run on untrusted input without giving it filesystem
// access.
//
// Run it with: go run ./examples/template_codegen
package main

import (
	"fmt"
	"log"
	"os"
	"sort"

	"simonwaldherr.de/go/nanogo/interp"
)

// guestProgram generates one Go file per entity in a small schema. The
// template holds the file layout; the loop supplies the data.
//
// As in examples/templates, the struct types are package level (nanoGo has no
// function-local type declarations) and slice elements spell out their type
// (`[]Field{Field{...}}` rather than Go's elided `[]Field{{...}}`).
const guestProgram = `package main

import (
	"fmt"
	"os"
	"strings"
	"text/template"
)

type Field struct {
	Name string
	Type string
}

type Entity struct {
	Name   string
	Fields []Field
}

// fileTemplate is parsed once and executed per entity: nanoGo caches the
// compiled template, so generating a hundred files costs one parse.
const fileTemplate = ` + "`" + `// Code generated by template_codegen. DO NOT EDIT.

package model

// {{.Name}} is a generated model type.
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}}
{{- end}}
}

// New{{.Name}} returns a zero-valued {{.Name}}.
func New{{.Name}}() {{.Name}} {
	return {{.Name}}{}
}
` + "`" + `

func main() {
	entities := []Entity{
		Entity{Name: "User", Fields: []Field{
			Field{Name: "ID", Type: "int"},
			Field{Name: "Email", Type: "string"},
		}},
		Entity{Name: "Order", Fields: []Field{
			Field{Name: "ID", Type: "int"},
			Field{Name: "Total", Type: "int"},
			Field{Name: "Paid", Type: "bool"},
		}},
	}

	if err := os.MkdirAll("/gen/model", 0755); err != nil {
		fmt.Println("mkdir failed:", err)
		return
	}

	for i := 0; i < len(entities); i++ {
		source, err := template.RenderString(fileTemplate, entities[i])
		if err != nil {
			fmt.Println("render failed:", err)
			return
		}
		name := "/gen/model/" + strings.ToLower(entities[i].Name) + ".go"
		if _, err := os.WriteFile(name, source, 0644); err != nil {
			fmt.Println("write failed:", err)
			return
		}
		fmt.Printf("generated %s (%d bytes)", name, len(source))
	}
}
`

func main() {
	vm := interp.NewInterpreter()

	// The generator needs to create directories and write files. Grant only
	// the filesystem capability; network access stays denied at its
	// zero value.
	vm.Capabilities.FileSystem = interp.FileSystemCapabilities{Read: true, Write: true}
	interp.RegisterBuiltinPackages(vm)

	vm.RegisterNative("ConsoleLog", func(args []any) (any, error) {
		if len(args) > 0 {
			fmt.Fprintln(os.Stdout, interp.ToString(args[0]))
		}
		return nil, nil
	})
	vm.RegisterNative("__hostSprintf", func(args []any) (any, error) {
		if len(args) == 0 {
			return "", nil
		}
		return fmt.Sprintf(interp.ToString(args[0]), args[1:]...), nil
	})

	if err := vm.Run(guestProgram); err != nil {
		log.Fatal(err)
	}

	// Read the generated tree back out of the VFS. This is the host side of
	// the sandbox: the guest never saw a real path.
	entries, err := vm.VFS.ReadDir("/gen/model")
	if err != nil {
		log.Fatal(err)
	}
	names := make([]string, 0, len(entries))
	for _, entry := range entries {
		names = append(names, entry.Name)
	}
	sort.Strings(names)

	for _, name := range names {
		content, err := vm.VFS.ReadFile("/gen/model/" + name)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("\n----- /gen/model/%s -----\n%s", name, content)
	}
}
